### ISSUE TITLE
Add some form of pagination to home page

### ISSUE THREAD

**Issue by ndubs18** [ethanSE/cryptoViewer#7]

**Comment by ndubs18** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#7 Add some form of pagination to home page](https://trello.com/c/fXSVc9uf/5-7-add-some-form-of-pagination-to-home-page)

**Comment by ndubs18** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#7 Add some form of pagination to home page](https://trello.com/c/fXSVc9uf/5-7-add-some-form-of-pagination-to-home-page)

**Comment by ethanSE** [comment]
It looks like we want users to be able to view a list cryptocurrencies that is paginated. We want them to be able to click through pages and view more results. Users should be able to select relative pages (previous/next) or absolute pages (page 1, page 5, etc).

The page a user is on should affect what is displayed in the list.

simplest approach:
Query for a bunch of data at once, split it up, and display parts of it based on what page the user is on. We could just get 1,000 results, chop it into lists of 100 and display one of these lists depending on what page the user is on.

More advanced:
don't request the data until the user requests it.
Query the API depending on what page the user is on. Memoize the results so that we don't have to make the same query multiple times. The API is paginated, our display is paginated, these can line up. If we query the API for page 4 once, we might not need to do it again while the app is running.

**Comment by ethanSE** [comment]
here's a hook that fetches coin data. It fetches 5 pages of 100 results per page.

```react
useEffect(() => {
    const pageNumbers = [1, 2, 3, 4, 5];

    Promise.all(
      pageNumbers.map((pageNumber) =>
        fetch(
          `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=${pageNumber}&price_change_percentage=24`
        ).then((res) => res.json())
      )
    )
      .then((results) => {
        setCoinData(results);
      })
      .catch((e) => console.log(e));
  }, []);
```
